version: '3.7'
services:
  postgresql:
    image: postgres:13-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: test_db
      POSTGRES_USER: test_test
      POSTGRES_PASSWORD: userTest1